// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9SO41ny0ZMASCc9eSNVPZ_noSVTa609s',
    appId: '1:694310204931:android:ffbc076cc5beae31414036',
    messagingSenderId: '694310204931',
    projectId: 'disaster-delivery-app',
    storageBucket: 'disaster-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIetUPBYAbOudsL2Dh4WqH8c_p_j1Gick',
    appId: '1:694310204931:web:7f6a2bff4572ced8414036',
    messagingSenderId: '694310204931',
    projectId: 'disaster-delivery-app',
    authDomain: 'disaster-delivery-app.firebaseapp.com',
    storageBucket: 'disaster-delivery-app.firebasestorage.app',
    measurementId: 'G-8RFYLHRBDC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClqJmTaE6bFLbgiwetxEBquxzbgY7x8jw',
    appId: '1:694310204931:ios:3eba4af2b814b7ed414036',
    messagingSenderId: '694310204931',
    projectId: 'disaster-delivery-app',
    storageBucket: 'disaster-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.disasterDelivery',
  );

}